# Generated by Django 3.2.3 on 2021-05-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('DesignerId', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('contactnumber', models.CharField(max_length=12)),
                ('designeremailid', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
